### PR TITLE
&.log -> self.log

### LINKED ISSUE #37: Cannot install Template::Mustache with rakudo 2019.11
```
❯ raku -v
This is Rakudo version 2019.11 built on MoarVM version 2019.11
implementing Perl 6.d.

❯ zef install --/test Template::Mustache
===> Searching for: Template::Mustache
===> Installing: Template::Mustache:ver<1.2.1>:auth<github:softmoth>
===> Install [FAIL] for Template::Mustache:ver<1.2.1>:auth<github:softmoth>: ===SORRY!=== Error while compiling /Users/skaji/try/20200719/site#sources/79E3FB3E714BBAD29F62C6D49C2D17898903B5B7 (Template::Mustache)
Confused
at /Users/skaji/try/20200719/site#sources/79E3FB3E714BBAD29F62C6D49C2D17898903B5B7 (Template::Mustache):150
------>                             &.log:⏏ :level<Trace>, "*****", $f.raku;
    expecting any of:
        colon pair

===SORRY!=== Error while compiling /Users/skaji/try/20200719/site#sources/79E3FB3E714BBAD29F62C6D49C2D17898903B5B7 (Template::Mustache)
Confused
at /Users/skaji/try/20200719/site#sources/79E3FB3E714BBAD29F62C6D49C2D17898903B5B7 (Template::Mustache):150
------>                             &.log:⏏ :level<Trace>, "*****", $f.raku;
    expecting any of:
        colon pair
```

If  Template::Mustache does not support rakudo 2019.11 intentionally, feel free to close this issue.

### PR DESCRIPTION
**Pull request by skaji**
Fix #37

### CODE REVIEW

**Comment by softmoth** [comment]
Thank you, skaji!

**Comment by skaji** [comment]
@softmoth Could you release a new version to CPAN?

**Comment by softmoth** [comment]
This is released in 1.2.2

**Comment by skaji** [comment]
@softmoth Thanks!

**Pull request merged**
